### ISSUE TITLE
deploy svelte generated website

### ISSUE THREAD

**Issue by malhotramanik** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#71]

**Comment by eddiejaoude** [comment]
Thank you creating the issue @malhotramanik 👍 

Currently the svelte website is generated on the command `npm run build` into the `public` directory. On GitHub Pages the only directories that are deployed are `/` (root) and `docs/`.

We could use a GitHub Action to deploy to a branch from any folder:

```yaml
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
```

https://github.com/marketplace/actions/deploy-to-github-pages
